version: 0.2
files:
  - source: .
    destination: /home/ec2-user/pipeline/
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 600
  ValidateService:
    - location: validate.sh
      timeout: 600
