version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/pipeline/
permissions:
  - object: /home/ec2-user/pipeline/
    mode: 777
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 300
      runas: ec2-use
  ValidateService:
    - location: validate.sh
      timeout: 300
      runas: ec2-user
