version: 0.0

phases:
  #pre_build:
  #  commands:
  #    - echo Setting up kubeconfig...
  #    - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
  build:
    commands:
      - echo Applying Kubernetes manifests...
      - kubectl apply -f k8s/
