version: 0.0

phases:
  build:
    commands:
      - echo Applying Kubernetes manifests...
      - pwd
      - ls -lrt
      - echo "Checking for k8s directory..."
      - if [ -d "k8s" ]; then echo "k8s directory found, running deploy.sh..."; bash ~/deploy.sh; else echo "k8s directory not found, skipping deploy.sh"; fi
